[project]
name = "claude-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "claude-agent-sdk>=0.1.6",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
]
