[project]
name = "coding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "ipykernel>=7.1.0",
    "openai>=2.8.0",
    "openai-agents>=0.5.1",
]
